name: LinuxCourse Workflow

on:
  - push
  - pull_request

jobs:
  task07:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO"

  check-gcc-version:
    runs-on: ubuntu-latest
    steps:
      - run: ghc --version | tee ghc-version.txt

  build:
    name: Autograding
    runs-on: ubuntu-latest
    needs:
      - task07
      - check-gcc-version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: apt install cmatrix
      - run: echo "autograding emulator"
